export const EMPLOYEES_FETCH_REQUESTED = "EMPLOYEE_FETCH_REQUESTED";
export const EMPLOYEES_FETCH_SUCCESSED = "EMPLOYEE_FETCH_SUCCESSED";
export const EMPLOYEES_FETCH_FAILED = "EMPLOYEE_FETCH_FAILED";
export const EMPLOYEES_GET_LIST = "EMPLOYEES_GET_LIST";
